version: '3'
services:
  backend:
    container_name: diaries-be
    image: diaries-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - docker-network
  
  db:
    container_name: diaries-db
    image: diaries-mongodb
    build:
      context: ./mongo-dev
      dockerfile: Dockerfile
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge